<script setup lang="ts">
import { ref,onMounted,computed } from 'vue'
import { useRouter } from 'vue-router'
import { state,refreshDashboard,notify } from '../store'
import { post } from '../api'
import Icon from '../components/Icon.vue'
import { formatSkillScore, skillScore } from '../scores'
import Tutor from '../components/Tutor.vue'
const router=useRouter(),loading=ref(true),error=ref(''),busy=ref(false),tutorOpen=ref(false)
const dashboard=computed(()=>state.dashboard);const rec=computed(()=>dashboard.value?.recommendation)
const orbit=computed(()=>{const all=dashboard.value?.abilities||[];const chosen=all.find((a:any)=>a.id===rec.value?.ability_id);const others=all.filter((a:any)=>a!==chosen).slice(0,4);return [others[0],others[1],chosen,others[2],others[3]].filter(Boolean)})
async function load(){loading.value=true;error.value='';try{await refreshDashboard()}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
onMounted(load)
async function start(){busy.value=true;try{const r=await post('/runs/start',{level_id:rec.value.level.id});router.push('/train/'+r.id)}catch(e){notify((e as Error).message,'error')}finally{busy.value=false}}
</script>
<template><div class="home-page content-width" :class="{'home-ai-open':tutorOpen}"><div class="home-welcome"><h1>欢迎回来，{{state.user?.name}}！</h1><span>{{state.user?.goal}}<span class="dot-separator">·</span>每天 {{state.user?.daily_goal}} 分钟</span></div><div v-if="error" class="empty-state"><Icon name="CircleHelp" :size="32"/><p>{{error}}</p><button class="btn outline" @click="load">重新加载</button></div><div v-else-if="loading" class="loading-state"><Icon name="LoaderCircle" class="spin"/>正在准备你的学习空间…</div><template v-else-if="rec&&dashboard"><section class="recommendation-stage"><div class="ability-orbit" aria-label="推荐能力"><RouterLink v-for="a in orbit" :key="a.id" :to="'/skills/'+a.id" :aria-label="a.name" class="orbit-icon" :class="{selected:a.id===rec.ability_id}"><Icon :name="a.icon" :size="a.id===rec.ability_id?64:27"/><span v-if="a.id===rec.ability_id" class="sparkle-one">✦</span></RouterLink></div><div class="recommendation-card"><span class="rec-kicker">为你推荐的下一步</span><h2>{{rec.ability_name}}</h2><div class="level-label">第 {{rec.level.mode==='course'?rec.level.id.split('L')[1]:rec.level.mode==='job'?'6':'7'}} 关</div><div class="progress-line"><span :style="{width:skillScore(rec.skill_score)*10+'%'}"></span></div><div class="rec-progress-note"><Icon name="Zap" :size="16"/>技能分 {{formatSkillScore(rec.skill_score)}} / 10 分 · 随答题正确率更新</div><div class="rec-lesson"><span class="lesson-medallion"><Icon :name="rec.level.mode==='course'?'BookOpen':rec.level.mode==='job'?'BriefcaseBusiness':'Trophy'" :size="26"/></span><div><strong>{{rec.level.name}}</strong><small>{{rec.level.count}} 道互动练习 · 约 {{rec.level.minutes}} 分钟</small></div><span class="pill purple">{{rec.level.mode==='course'?'课':rec.level.mode==='job'?'岗':'赛'}}</span></div><button class="btn rec-start" :disabled="busy" @click="start">{{busy?'准备中…':'开始训练'}}<Icon name="ArrowRight"/></button></div></section><div class="home-tutor"><Tutor stage @open-change="tutorOpen=$event"/></div><div class="home-links"><RouterLink to="/skills">探索完整技能地图<Icon name="ArrowRight" :size="15"/></RouterLink></div><section v-if="dashboard.active_run" class="resume-strip"><Icon name="Play" :size="18"/><p>上次的训练还在这里：已完成 {{dashboard.active_run.answered}} / {{dashboard.active_run.count}} 题</p><RouterLink :to="'/train/'+dashboard.active_run.id">继续训练<Icon name="ArrowRight" :size="16"/></RouterLink></section><p class="home-footnote">{{rec.reason}}</p></template></div></template>
