<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { post } from '../api'
import { state } from '../store'
import Icon from '../components/Icon.vue'
const router=useRouter();const username=ref('');const password=ref('');const error=ref('');const busy=ref(false)
async function login(){error.value='';busy.value=true;try {state.user=await post('/auth/login',{username:username.value,password:password.value});await router.push(state.user?.role==='admin'?'/admin':state.user?.onboarding?'/':'/onboarding')}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><div class="login-page"><section class="login-story"><a class="brand" href="/login"><img src="/favicon.svg" alt=""><span>智基<span class="brand-dot">.</span></span></a><div class="story-copy"><span class="eyebrow">AI 数据标注师 · 互动学习平台</span><h1>每一次动手，<br>都让未来<span>更清晰。</span></h1><p>从你的第一个标注框开始，<br>把好奇心，一步步变成真本领。</p><div class="learning-diagram" aria-label="从观察、标注到掌握的学习过程"><div><Icon name="ScanEye" :size="34"/><span>看见</span></div><i></i><div class="highlight"><Icon name="SquareDashed" :size="38"/><span>动手</span></div><i></i><div><Icon name="Lightbulb" :size="34"/><span>学会</span></div></div><div class="story-chips"><span><Icon name="Check" :size="16"/> 零基础也能开始</span><span><Icon name="Check" :size="16"/> 边练边学，即时反馈</span></div></div><div class="story-footer">从课堂练习，走向真实岗位。</div></section><section class="login-form-side"><form @submit.prevent="login" class="login-form"><span class="pill lime">欢迎来到智基</span><h2>准备好，学点真本领。</h2><p class="muted">登录账号，开启你的技能成长之旅。</p><label for="username">用户名</label><input id="username" v-model.trim="username" autocomplete="username" placeholder="请输入你的用户名" required maxlength="40"><label for="password">密码</label><input id="password" type="password" v-model="password" autocomplete="current-password" placeholder="请输入密码" required maxlength="128"><div v-if="error" class="error-message" role="alert">{{error}}</div><button class="btn dark full" :disabled="busy">{{busy?'正在登录…':'登录，开始学习'}}<Icon :name="busy?'LoaderCircle':'ArrowRight'" :class="{spin:busy}"/></button><div class="account-hint"><Icon name="CircleHelp" :size="18"/><p>使用老师分配的学习账号登录。<br><span>首次登录会带你完成一次轻松的标注体验。</span></p></div></form><p class="login-footer">智基 · 让每一步成长，都有迹可循</p></section></div></template>
