<script setup lang="ts">
import { ref,onMounted,onBeforeUnmount,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { api,post } from '../api'
import { notify } from '../store'
import Icon from '../components/Icon.vue'
const route=useRoute(),router=useRouter(),data=ref<any>(),error=ref(''),busy=ref(''),update=ref<any>();let poll:ReturnType<typeof setInterval>|undefined
async function load(){try{data.value=await api('/abilities/'+route.params.id);if(data.value.update?.status==='running'){update.value=data.value.update;pollUpdate()}}catch(e){error.value=(e as Error).message}}
watch(()=>route.params.id,()=>{clearInterval(poll);data.value=undefined;update.value=undefined;error.value='';load()});onMounted(load);onBeforeUnmount(()=>clearInterval(poll))
async function start(level:any){if(!level.unlocked||update.value?.status==='running')return;busy.value=level.id;try{const run=await post('/runs/start',{level_id:level.id});router.push('/train/'+run.id)}catch(e){notify((e as Error).message,'error')}finally{busy.value=''}}
async function refresh(){try{update.value=await post(`/abilities/${route.params.id}/refresh`);pollUpdate()}catch(e){notify((e as Error).message,'error')}}
function pollUpdate(){clearInterval(poll);poll=setInterval(async()=>{try{update.value=await api(`/abilities/${route.params.id}/refresh`);if(update.value.status!=='running'){clearInterval(poll);if(update.value.status==='completed'){notify('新题集已就绪，可以开始训练了。');await load()}else notify(update.value.stage,'error')}}catch(e){clearInterval(poll);notify((e as Error).message,'error')}},700)}
</script>
<template><div class="content-width module-page"><header class="module-toolbar"><RouterLink to="/skills" class="back-link"><Icon name="ArrowLeft" :size="18"/>返回技能地图</RouterLink><button class="btn outline small" :disabled="update?.status==='running'" @click="refresh"><Icon name="RefreshCw" :size="16" :class="{spin:update?.status==='running'}"/>{{update?.status==='running'?`更新中 ${update.progress}%`:'更新题目'}}</button></header><div v-if="error" class="error-message">{{error}}</div><div v-if="update?.status==='running'" class="update-banner" role="status"><div><Icon name="RefreshCw" class="spin"/>{{update.stage}}<b>{{update.progress}}%</b></div><div class="progress-line"><span :style="{width:update.progress+'%'}"></span></div></div><div v-if="data" class="module-layout"><aside class="module-info"><div class="module-icon" :class="data.color"><Icon :name="data.icon" :size="72"/></div><span class="eyebrow">{{data.id}} · 能力训练</span><h1>{{data.name}}</h1><p>{{data.description}}</p><div class="course-meta"><span><Icon name="Layers3" :size="17"/>7 个关卡</span><span><Icon name="Shapes" :size="17"/>55 道练习</span></div><div class="module-mastery"><span>能力掌握度<b>{{data.mastery}}%</b></span><div class="progress-line"><span :style="{width:data.mastery+'%'}"></span></div></div><div class="mode-legend"><span><b class="pill purple">课</b>分步学会</span><span><b class="pill orange">岗</b>整包实战</span><span><b class="pill lime">赛</b>限时挑战</span></div><small class="version-note">题集版本 {{data.version}} · 完成记录独立保留</small></aside><section class="level-path" aria-label="关卡路径"><div v-for="(level,i) in data.levels" :key="level.id" class="level-step" :class="{locked:!level.unlocked,current:level.unlocked&&!level.completed,completed:level.completed}" :style="{'--shift': [0,-48,42,-24,36,-18,0][Number(i)]+'px'}"><div class="level-connector" v-if="Number(i)<data.levels.length-1"></div><div class="level-section-caption" v-if="i===0||level.mode!=='course'"><b>{{level.mode==='course'?'第 1 阶段':level.mode==='job'?'第 2 阶段':'最终挑战'}}</b><span>{{level.mode==='course'?'理解与练习':level.mode==='job'?'岗位实战':'技能竞赛'}}</span></div><button class="level-hit" :disabled="!level.unlocked||!!busy||update?.status==='running'" @click="start(level)" :aria-label="`${level.name}，${level.completed?'已完成':level.unlocked?'开始训练':'尚未解锁'}`"><span class="level-coin"><Icon :name="busy===level.id?'LoaderCircle':!level.unlocked?'LockKeyhole':level.completed?'Check':level.mode==='job'?'BriefcaseBusiness':level.mode==='competition'?'Trophy':'BookOpen'" :size="30" :class="{spin:busy===level.id}"/></span><span class="level-name"><strong>{{level.name}}</strong><small>{{level.completed?`已完成 · 得分 ${Math.round(level.score)}%`:!level.unlocked?'完成前置关卡后解锁':`${level.count} 道练习 · 约 ${level.minutes} 分钟`}}</small></span><span v-if="level.unlocked&&!level.completed" class="level-go"><Icon name="Play" :size="15"/></span></button></div></section></div></div></template>
