<script setup lang="ts">
import { ref,onMounted } from 'vue'
import { api } from '../api'
import Icon from '../components/Icon.vue'
const abilities=ref<any[]>([]),error=ref('')
onMounted(async()=>{try{abilities.value=await api('/abilities')}catch(e){error.value=(e as Error).message}})
const positions:Record<string,{x:number;y:number}>={A1:{x:450,y:70},A2:{x:450,y:215},A3:{x:210,y:370},A4:{x:690,y:370},A8:{x:210,y:545},A5:{x:690,y:545},A6:{x:490,y:705},A7:{x:870,y:705},A9:{x:450,y:900},A10:{x:450,y:1065}}
const edges=[['A1','A2'],['A2','A3'],['A2','A4'],['A3','A8'],['A4','A5'],['A5','A6'],['A5','A7'],['A8','A9'],['A6','A9'],['A7','A9'],['A9','A10']]
function line(from:string,to:string){const a=positions[from],b=positions[to];return `M ${a.x} ${a.y+45} C ${a.x} ${a.y+(b.y-a.y)/2} ${b.x} ${a.y+(b.y-a.y)/2} ${b.x} ${b.y-42}`}
</script>
<template><div class="content-width skills-page"><header class="section-heading"><div><span class="eyebrow">从基础认知，到项目交付</span><h1>你的技能地图</h1><p class="muted">沿着知识的脉络，一步一步建立真本领。</p></div><RouterLink to="/tasks" class="btn outline"><Icon name="BriefcaseBusiness" :size="18"/>企业任务转教学</RouterLink></header><div v-if="error" class="error-message">{{error}}</div><div class="map-legend"><span><i class="legend-dot violet"></i>可探索</span><span><i class="legend-dot green"></i>已掌握</span><span>箭头表示前置知识关系，点击节点开始学习</span></div><div class="skill-map-scroll"><div class="skill-map"><svg class="map-lines" viewBox="0 0 1080 1160" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="arrow" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#b59be9"/></marker></defs><path v-for="[a,b] in edges" :key="a+b" :d="line(a!,b!)" fill="none" stroke="#c8b6ee" stroke-width="3" marker-end="url(#arrow)"/></svg><RouterLink v-for="a in abilities" :key="a.id" :to="'/skills/'+a.id" class="skill-node" :class="[a.color,{'mastered':a.mastery>=80}]" :style="{left:positions[a.id]!.x/1080*100+'%',top:positions[a.id]!.y+'px'}"><span class="skill-platform"><Icon :name="a.icon" :size="40"/></span><span class="skill-node-label"><small>{{a.id}}</small><strong>{{a.name}}</strong><span class="node-mastery"><span class="tiny-progress"><i :style="{width:a.mastery+'%'}"></i></span>{{a.mastery}}%</span></span></RouterLink></div></div><div class="map-footer"><Icon name="Lightbulb"/><p>掌握度综合入门诊断与近期训练结果。先练基础，再探索分支；首页会随你的掌握情况调整推荐。</p></div></div></template>
