<script setup lang="ts">
import { ref,computed,onMounted,onBeforeUnmount,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { api,post } from '../api'
import { state,notify,prepareEncouragement,encourage,toggleVoice,refreshDashboard } from '../store'
import Icon from '../components/Icon.vue'
import QuestionInput from '../components/QuestionInput.vue'
import Tutor from '../components/Tutor.vue'
import { stopEncouragementAudio } from '../audio'
import { formatSkillScore } from '../scores'
const liveSkill=ref<any>(),audioNotice=ref('')
let alive=true,viewRevision=0
function isCurrent(revision:number){return alive&&revision===viewRevision}
function invalidateView(){viewRevision++;stopEncouragementAudio();audioNotice.value=''}
async function playReward(revision=viewRevision){if(!isCurrent(revision))return;const status=await encourage();if(isCurrent(revision))audioNotice.value=status==='played'?'鼓励语音已播放':status==='unavailable'?'鼓励语音暂不可用':''}
async function loadSkill(revision=viewRevision){if(!run.value||batch.value||!isCurrent(revision))return;try{const skill=await api('/abilities/'+run.value.ability_id);if(isCurrent(revision))liveSkill.value=skill}catch{if(isCurrent(revision))liveSkill.value=undefined}}
const route=useRoute(),router=useRouter(),run=ref<any>(),index=ref(0),answer=ref<any>({}),feedback=ref<any>(),busy=ref(false),error=ref(''),intro=ref(true),exitDialog=ref(false),showStandard=ref(false),nowMs=ref(Date.now()),timeOffset=ref(0),inspect=ref(''),tutorOpen=ref(false),coachMessage=ref('')
let interval:ReturnType<typeof setInterval>|undefined
const q=computed(()=>run.value?.questions[index.value]);const mode=computed(()=>run.value?.mode);const batch=computed(()=>mode.value==='job'||mode.value==='competition');const report=computed(()=>run.value?.report);const finished=computed(()=>run.value?.status==='completed');const remaining=computed(()=>run.value?.deadline?Math.max(0,Math.ceil((Date.parse(run.value.deadline)-(nowMs.value+timeOffset.value))/1000)):0);const clock=computed(()=>`${Math.floor(remaining.value/60).toString().padStart(2,'0')}:${(remaining.value%60).toString().padStart(2,'0')}`)
const validAnswer=computed(()=>{if(!q.value)return false;if(q.value.type==='box')return answer.value.boxes?.length&&answer.value.boxes.every((b:any)=>b.label);if(q.value.type==='polygon')return answer.value.points?.length>=3&&answer.value.label;if(q.value.type==='entity')return answer.value.start!==undefined&&answer.value.label;return !!answer.value.value})
const completedQuestionCount=computed(()=>{if(!run.value)return 0;if(batch.value)return Object.keys(run.value.answers).length;return run.value.questions.filter((item:any)=>run.value.question_status?.[item.id]==='correct').length})
const jobReturn=computed(()=>typeof route.query.taskId==='string'&&typeof route.query.roleId==='string'?`/jobs/${encodeURIComponent(route.query.roleId)}/tasks/${encodeURIComponent(route.query.taskId)}`:run.value?.job_learning?.task_id?`/jobs/${encodeURIComponent(run.value.job_learning.role_id)}/tasks/${encodeURIComponent(run.value.job_learning.task_id)}`:run.value?.job_learning?`/jobs/${encodeURIComponent(run.value.job_learning.role_id)}/learn/${encodeURIComponent(run.value.job_learning.learning_id)}`:typeof route.query.jobLearning==='string'&&typeof route.query.roleId==='string'?`/jobs/${encodeURIComponent(route.query.roleId)}/learn/${encodeURIComponent(route.query.jobLearning)}`:typeof route.query.roleId==='string'?`/jobs/${encodeURIComponent(route.query.roleId)}`:'')
const modeName=computed(()=>mode.value==='job'?'岗位实战':mode.value==='competition'?'限时挑战':'互动课堂')
async function load(){const revision=viewRevision;error.value='';try{const loaded=await api('/runs/'+route.params.id);if(!isCurrent(revision))return;run.value=loaded;timeOffset.value=Date.parse(run.value.server_time)-Date.now();const pending=run.value.questions.findIndex((item:any)=>batch.value?!run.value.answers[item.id]:run.value.question_status?.[item.id]!=='correct');index.value=pending>=0?pending:0;answer.value=run.value.answers[q.value.id]||{};intro.value=!Object.keys(run.value.answers).length&&!finished.value;await loadSkill(revision)}catch(e){if(isCurrent(revision))error.value=(e as Error).message}}
onMounted(()=>{load();interval=setInterval(async()=>{nowMs.value=Date.now();if(run.value?.deadline&&remaining.value===0&&!finished.value&&!busy.value){await finish(true)}},1000)})
onBeforeUnmount(()=>{alive=false;invalidateView();clearInterval(interval)})
watch(()=>route.params.id,()=>{invalidateView();run.value=undefined;feedback.value=null;showStandard.value=false;busy.value=false;load()})
async function submit(){if(busy.value||!run.value||!q.value)return;prepareEncouragement();const revision=viewRevision,runId=run.value.id,questionId=q.value.id,submittedAnswer=JSON.parse(JSON.stringify(answer.value));busy.value=true;error.value='';audioNotice.value='';coachMessage.value='';try{const r=await post(`/runs/${runId}/answer`,{question_id:questionId,answer:submittedAnswer});if(!isCurrent(revision))return;run.value.answers={...run.value.answers,[questionId]:submittedAnswer};if(batch.value){notify('标注已保存');if(index.value<run.value.questions.length-1)go(index.value+1,true)}else{run.value.question_status={...(run.value.question_status||{}),[questionId]:r.result.correct?'correct':'incorrect'};feedback.value={...r.result,wrong_attempts:r.wrong_attempts||0};coachMessage.value=r.coach_encouragement||'';if(r.result.correct)void playReward(revision);await loadSkill(revision)}}catch(e){if(!isCurrent(revision))return;error.value=(e as Error).message;if((e as any).status===409)await load()}finally{if(isCurrent(revision))busy.value=false}}
function go(i:number,afterSave=false){if(busy.value&&!afterSave)return;if(!run.value||i<0||i>=run.value.questions.length)return;invalidateView();busy.value=false;index.value=i;answer.value=JSON.parse(JSON.stringify(run.value.answers[q.value.id]||{}));feedback.value=null;coachMessage.value='';showStandard.value=false;error.value=''}
async function next(){if(!batch.value&&!feedback.value?.correct)return;if(index.value<run.value.questions.length-1)go(index.value+1);else await finish()}
async function finish(timeout=false){if(busy.value||!run.value)return;if(!timeout)prepareEncouragement();const revision=viewRevision,runId=run.value.id;busy.value=true;error.value='';try{const completed=await post(`/runs/${runId}/finish`);if(!isCurrent(revision))return;run.value=completed;intro.value=false;await refreshDashboard();if(!isCurrent(revision))return;if(timeout)notify('时间到，系统已自动提交并生成结果。');if(batch.value&&run.value.report.passed)void playReward(revision)}catch(e){if(isCurrent(revision))error.value=(e as Error).message}finally{if(isCurrent(revision))busy.value=false}}
async function repair(){if(busy.value)return;const revision=viewRevision;busy.value=true;try{const r=await post(`/runs/${run.value.id}/repair`);if(isCurrent(revision))await router.replace({path:'/train/'+r.id,query:route.query})}catch(e){if(isCurrent(revision))error.value=(e as Error).message}finally{if(isCurrent(revision))busy.value=false}}
function downloadReport(){const blob=new Blob([JSON.stringify({platform:'智基',report:report.value,task_id:run.value.id,ability_id:run.value.ability_id},null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`智基-训练报告-${run.value.id.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
</script>
<template><div class="training-page" :class="{'batch-mode':batch&&!finished,'tutor-panel-open':tutorOpen&&!batch&&!finished&&!intro}"><header class="learning-header"><button class="icon-button" @click="exitDialog=true" aria-label="退出训练"><Icon name="X"/></button><div class="training-progress"><span>{{modeName}}<small>{{run?.ability_id}}</small></span><div class="progress-line"><span :style="{width:run?(completedQuestionCount/run.questions.length*100)+'%':'0%'}"></span></div><b>{{completedQuestionCount}} / {{run?.questions.length||0}}</b></div><span v-if="mode==='competition'&&!finished" class="timer" :class="{urgent:remaining<60}"><Icon name="Clock3" :size="18"/>{{clock}}</span><button class="icon-button" @click="toggleVoice" :disabled="state.voiceSaving" :aria-pressed="!!state.user?.voice" :aria-label="state.user?.voice?'关闭答对鼓励':'开启答对鼓励'"><Icon :name="state.user?.voice?'Volume2':'VolumeX'"/></button></header><div v-if="!run" class="loading-state">{{error||'正在准备训练…'}}</div>
<section v-else-if="finished" class="report-page"><div class="report-emblem" :class="{passed:report.passed}"><Icon :name="report.passed?'Trophy':'ChartNoAxesCombined'" :size="48"/></div><span class="eyebrow">每次练习，都有收获</span><h1>{{mode==='job'?'岗位任务质量报告':mode==='competition'?'挑战结束，看看你的表现':'完成一关，离目标更近一步。'}}</h1><p class="muted">{{run.ability_id}} · {{modeName}}<span class="dot-separator">·</span>{{report.count}} 道题目{{run.revision_of?' · 返修复核':''}}</p><div class="report-score"><strong>{{Math.round(report.score)}}<small>分</small></strong><span :class="['pill',report.passed?'lime':'orange']"><Icon :name="report.passed?'Check':'RotateCcw'" :size="15"/>{{report.passed?'达到本项目训练要求':'还有可以提升的地方'}}</span></div><div class="report-metrics"><div><small>标签准确率</small><b>{{report.label_accuracy}}<span>%</span></b></div><div><small>平均交并比</small><b>{{report.average_iou===null?'不适用':report.average_iou}}<span v-if="report.average_iou!==null">%</span></b></div><div><small>漏标率</small><b>{{report.missed_rate}}<span>%</span></b></div><div><small>误标率</small><b>{{report.false_positive_rate}}<span>%</span></b></div></div><p class="report-criteria">{{report.criteria}}</p><section class="report-review"><h3>逐题复盘<span>{{report.correct_count}} / {{report.count}} 题通过</span></h3><div v-for="(r,i) in report.results" :key="r.question_id" class="review-item"><button @click="inspect=inspect===r.question_id?'':r.question_id"><span class="review-status" :class="{correct:r.correct}"><Icon :name="r.correct?'Check':'RotateCcw'" :size="16"/></span><span>第 {{Number(i)+1}} 题<span>{{r.title}}</span></span><b>{{Math.round(r.score)}} 分</b><Icon name="ChevronRight" :size="17"/></button><div v-if="inspect===r.question_id" class="review-detail"><p>{{r.feedback}}</p><p v-if="typeof r.standard_answer==='string'">参考答案：{{r.standard_answer}}</p><QuestionInput v-else :question="run.questions[Number(i)]" :model-value="run.answers[r.question_id]||{}" disabled :standard="r.standard_answer"/><p v-if="r.iou!==null" class="muted">区域交并比 {{(r.iou*100).toFixed(1)}}%<template v-if="r.boundary_iou!==undefined"> · 边界交并比 {{(r.boundary_iou*100).toFixed(1)}}%</template></p></div></div></section><div class="report-actions"><button class="btn outline" @click="downloadReport"><Icon name="Download" :size="17"/>下载报告</button><button v-if="mode==='job'&&report.correct_count<report.count" class="btn outline" :disabled="busy" @click="repair"><Icon name="RotateCcw" :size="17"/>开始返修</button><RouterLink v-if="jobReturn" :to="jobReturn" class="btn green">返回岗位任务<Icon name="ArrowRight" :size="18"/></RouterLink><RouterLink v-else :to="'/skills/'+run.ability_id" class="btn green">继续成长<Icon name="ArrowRight" :size="18"/></RouterLink></div></section>
<section v-else-if="intro" class="training-intro"><span class="intro-icon"><Icon :name="mode==='job'?'BriefcaseBusiness':mode==='competition'?'Trophy':'BookOpen'" :size="45"/></span><span class="pill purple">{{run.job_learning?'岗位任务 · 分步实操':modeName}}</span><p v-if="run.job_learning" class="job-skill-context">{{run.job_learning.title}} · 实操结果将用于当前岗位任务的验收</p><h1>{{mode==='job'?'像一位标注师一样，完成任务。':mode==='competition'?'准备好，迎接这次挑战。':'先理解，再动手。'}}</h1><p>{{mode==='job'?'这一次，你会连续处理一个完整任务包。完成后统一提交，系统会生成真实的质量报告。':mode==='competition'?'倒计时已经开始。独立完成任务，时间结束后系统会自动提交并评分。':'不必着急，认真观察每道题目。做错可以重试，遇到困难可以向小基要一点提示。'}}</p><div class="intro-specs"><span><Icon name="Layers3"/>{{run.questions.length}} {{mode==='job'?'个工作样本':'道互动题目'}}</span><span><Icon :name="batch?'FileCheck2':'MessageCircle'"/>{{batch?'提交后统一反馈':'每一步即时反馈'}}</span><span><Icon :name="mode==='competition'?'Clock3':'RotateCcw'"/>{{mode==='competition'?'限时 10 分钟':'按照自己的节奏'}}</span></div><div class="training-rule"><Icon name="CircleHelp"/><div><b>本次训练约定</b><p>阅读每题的目标与标签定义。框选题按指定对象的参考边界标注，区域交并比达到 65% 且类别准确时通过；多边形练习同样以 65% 区域重合作为入门标准。文本与分类题依据题中定义判定。</p><small>公开样本与原创岗位情境用于教学，具体企业项目以其正式规范为准。</small></div></div><button class="btn green" @click="prepareEncouragement();intro=false">{{mode==='job'?'进入标注工作台':'开始练习'}}<Icon name="ArrowRight" :size="18"/></button></section>
<div v-else class="exercise-layout"><aside v-if="batch" class="batch-sidebar"><div class="batch-project"><span class="pill" :class="mode==='job'?'orange':'purple'">{{mode==='job'?'岗':'赛'}}</span><b>{{run.ability_id}} 训练任务包</b><small>公开样本 · 岗位教学</small></div><div class="batch-list"><button v-for="(item,i) in run.questions" :key="item.id" :disabled="busy" :class="{active:index===i,saved:run.answers[item.id]}" @click="go(Number(i))"><Icon :name="run.answers[item.id]?'CheckCheck':item.image?'ScanLine':'FileCheck2'" :size="17"/><span>样本 {{String(Number(i)+1).padStart(2,'0')}}</span><small>{{run.answers[item.id]?'已保存':'待处理'}}</small></button></div><div class="batch-save-note"><Icon name="ShieldCheck" :size="16"/>已提交标注自动保存</div></aside><section class="exercise-content"><div class="exercise-topline"><span class="pill" :class="mode==='job'?'orange':'purple'">{{modeName}}</span><span>第 {{index+1}} / {{run.questions.length}} 题</span></div><h1>{{q.title}}</h1><p v-if="!batch" class="exercise-instruction">{{q.type==='choice'?'选择最符合任务规范的一项。':q.type==='entity'?'找出完整的实体，并为它选择正确的类型。':'仔细观察目标，然后完成你的标注。'}}</p><QuestionInput :key="q.id" :question="q" v-model="answer" :disabled="!!feedback||busy" :standard="showStandard?feedback?.standard_answer:undefined"/><div v-if="feedback" class="answer-feedback" :class="{correct:feedback.correct}"><Icon :name="feedback.correct?'Check':'Lightbulb'" :size="25"/><div><b>{{feedback.correct?'做得很好！':'还不完全对，再试一次。'}}</b><p>{{feedback.feedback}}</p><small v-if="!feedback.correct" class="retry-note">答对后才会进入下一题。</small><small v-if="liveSkill" class="live-skill-score" role="status">当前能力技能分 {{formatSkillScore(liveSkill.skill_score)}} / 10 分 · 已判定 {{liveSkill.answer_count}} 题</small><small v-if="audioNotice" class="audio-notice" role="status">{{audioNotice}}</small><span v-if="feedback.iou!==null">当前交并比 {{(feedback.iou*100).toFixed(1)}}%</span></div></div><div v-if="error" class="error-message" role="alert">{{error}}</div><p v-if="batch" class="batch-note"><Icon name="ShieldCheck" :size="14"/>保存单条记录不会判定对错。{{mode==='job'?'完成整个任务包后统一质检。':'比赛结束后统一公布结果。'}}</p></section></div>
<footer v-if="run&&!finished&&!intro" class="learning-footer"><div><button class="text-button" :disabled="busy||index===0" @click="go(index-1)"><Icon name="ArrowLeft" :size="16"/>上一题</button><div class="exercise-actions"><button v-if="feedback&&!feedback.correct" class="btn green retry-action" @click="feedback=null;showStandard=false">再试一次<Icon name="RotateCcw" :size="18"/></button><button v-if="feedback?.correct" class="btn green" @click="next" :disabled="busy">{{index<run.questions.length-1?'继续':'完成训练'}}<Icon name="ArrowRight" :size="18"/></button><button v-if="!feedback" class="btn green" @click="submit" :disabled="busy||!validAnswer">{{busy?'保存中…':batch?'保存标注':'检查答案'}}<Icon name="Check" :size="18"/></button><button v-if="batch&&Object.keys(run.answers).length===run.questions.length" class="btn dark" @click="finish()" :disabled="busy">提交任务包<Icon name="ArrowRight" :size="18"/></button></div></div></footer><Tutor v-if="run&&!intro&&!finished&&mode!=='competition'" floating :run-id="run.id" :question-id="q.id" :nudge="coachMessage" @open-change="tutorOpen=$event"/>
<div v-if="exitDialog" class="modal-backdrop" @click.self="exitDialog=false"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="exit-title"><h2 id="exit-title">先休息一下？</h2><p>已提交的标注会保留，你可以随时回来继续。{{mode==='competition'&&!finished?'比赛倒计时会继续，结束后自动结算。':''}}</p><div class="modal-actions"><button class="btn outline" @click="exitDialog=false">继续训练</button><button class="btn dark" @click="router.push(jobReturn||'/skills/'+run?.ability_id)">保存并退出</button></div></section></div></div></template>

<style scoped>.live-skill-score,.audio-notice{display:block;margin-top:7px;color:#61725d;font-size:12px}</style>
