<script setup lang="ts">
import { ref,watch } from 'vue'
import AnnotationCanvas from './AnnotationCanvas.vue'
import Icon from './Icon.vue'
const props=withDefaults(defineProps<{question:any;modelValue:any;disabled?:boolean;standard?:any}>(),{disabled:false})
const emit=defineEmits(['update:modelValue']);const anchor=ref<number|null>(null);const focus=ref<number|null>(null),label=ref('')
watch(()=>props.question.id,()=>{anchor.value=null;focus.value=null;label.value=''})
watch(()=>props.modelValue,v=>{if(v?.label)label.value=v.label;if(anchor.value===null&&v?.start!==undefined){anchor.value=v.start;focus.value=v.end-1}},{immediate:true})
function charClick(i:number){if(props.disabled)return;if(anchor.value===null||focus.value!==null){anchor.value=i;focus.value=null;emit('update:modelValue',{})}else{focus.value=i;emitValue()}}
function emitValue(){if(anchor.value!==null)emit('update:modelValue',{start:Math.min(anchor.value,focus.value??anchor.value),end:Math.max(anchor.value,focus.value??anchor.value)+1,label:label.value})}
function isSelected(i:number){return props.modelValue?.start!==undefined?i>=props.modelValue.start&&i<props.modelValue.end:anchor.value===i}
</script>
<template><AnnotationCanvas v-if="['box','polygon'].includes(question.type)" :question="question" :model-value="modelValue" @update:model-value="emit('update:modelValue',$event)" :disabled="disabled" :standard="standard"/><div v-else-if="question.type==='entity'" class="entity-exercise"><p>点击实体的第一个字，再点击最后一个字。</p><div class="entity-sentence"><button v-for="(char,i) in question.text.split('')" :key="i" :disabled="disabled" :class="{selected:isSelected(Number(i)),anchor:anchor===i&&focus===null}" @click="charClick(Number(i))" :aria-label="`第 ${Number(i)+1} 个字：${char}`">{{char}}</button></div><div class="entity-labels"><button v-for="l in question.labels" :key="l" :disabled="disabled" class="label-chip" :class="{selected:label===l||modelValue?.label===l}" @click="label=l;emitValue()">{{l}}</button></div><p v-if="modelValue?.start!==undefined" class="entity-selection">已选择：<b>{{question.text.slice(modelValue.start,modelValue.end)}}</b> · {{modelValue.label||'请选择实体类型'}}</p><p v-if="standard" class="entity-selection">参考实体：<b>{{question.text.slice(standard.start,standard.end)}}</b> · {{standard.label}}</p></div><div v-else><figure v-if="question.image" class="classification-image"><img :src="question.image" alt="待分类的训练图片"><figcaption><a :href="question.source_url" target="_blank" rel="noopener noreferrer">素材来源</a></figcaption></figure><div class="choice-options"><button v-for="(option,i) in question.options" :key="option" :disabled="disabled" :class="['choice-option',{selected:modelValue?.value===option,correct:standard===option}]" @click="emit('update:modelValue',{value:option})"><span class="option-index">{{Number(i)+1}}</span><span>{{option}}</span><Icon v-if="modelValue?.value===option" name="Check" :size="20"/></button></div></div></template>
